service: notification-service

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  region: eu-west-1
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - ${file(iam/SendMailIAM.yml):SendMailIAM}

functions:
  sendMail:
    handler: src/handlers/sendMail.handler
